### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by Victor2806** [Victor2806/SEBC#2]

**Comment by Victor2806** [comment]
Prepared all instances  in AWS 
![image](https://cloud.githubusercontent.com/assets/28241886/25686743/efbb3e30-30b3-11e7-8969-ac0ebb42c387.png)

**Comment by Victor2806** [comment]
30 GB  volumes assigned 
![image](https://cloud.githubusercontent.com/assets/28241886/25686755/1ddc6bcc-30b4-11e7-9dda-2dce793fd8c2.png)

**Comment by Victor2806** [comment]
Installation Lab completed

**Comment by mfernest** [comment]
Good work!
